# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "cosmic-rescue"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true
stack_name = "CosmicRescueStack"
s3_prefix = "CosmicRescueStack"
region = "us-east-2"
parameter_overrides = "DBUser=\"postgres\" DBPassword=\"7F3x2D5fa29Emd\" DBHost=\"mlflow.cgtdf7yvdtuk.us-east-2.rds.amazonaws.com\" DBPort=\"5432\" DBName=\"postgres\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
